"""primera migracion

Revision ID: 223e9e0ba3e8
Revises: 
Create Date: 2024-10-14 02:10:07.004716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223e9e0ba3e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_email'), 'author', ['email'], unique=True)
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_index(op.f('ix_author_email'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
